// PatchMesh relay plugin for OpenCode.
// Generated by `patchmesh init --host opencode`; regenerate with --force after upgrading.
// Records every tool call to the local PatchMesh ledger. Every error is swallowed on
// purpose: recording may cost time, but it must never break a tool call.
import { spawnSync } from "node:child_process";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const RECORDER_BIN = "packages/recorder/dist/bin.js";
const RECORDER_RELATIVE = true;
const RECORDER_BARE = false;

// Repository root, derived from this file's own location: <root>/.opencode/plugins/
// patchmesh.mjs - two segments up from the directory leaves the repository root.
function repoRoot() {
  return fileURLToPath(new URL("../..", import.meta.url));
}

function record(stage) {
  return (input) => {
    try {
      const bin = RECORDER_RELATIVE ? join(repoRoot(), RECORDER_BIN) : RECORDER_BIN;
      // A baked path names a .js file, so it runs under this runtime's own interpreter;
      // a bare name is already an executable in its own right.
      const command = RECORDER_BARE ? bin : process.execPath;
      const recorderArgs = RECORDER_BARE ? [] : [bin];
      spawnSync(
        command,
        [...recorderArgs, "--host", "opencode"],
        {
          input: JSON.stringify({ stage, ...(input ?? {}) }),
          stdio: ["pipe", "ignore", "ignore"],
          timeout: 10000,
          shell: false,
        },
      );
    } catch {
      // Swallowed deliberately - see the header comment.
    }
  };
}

export const PatchMeshPlugin = async () => ({
  "tool.execute.before": record("before"),
  "tool.execute.after": record("after"),
});
